---
title: "Burgtheater & Kärntnertortheater, 1781"
author: "David Black and Dexter Edge"
date: "`r format(Sys.time(), '%e %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(DT)
library(lubridate)

calendar <- read_csv("Schletter.csv", col_names=FALSE,
                     na = c("", "NA"))
colnames(calendar) <- c("YMD", "Theater", "Company", "Title",
                          "Genre", "Author", "Composer")
  
calendar %>%
  # Change Filemaker date string to YYYY-MM-DD
  mutate(YMD = mdy(YMD)) %>% 
  # Add display date
  mutate(Date = format(YMD, "%a, %e %b"), .before = YMD) %>% 
  # Drop rows with blank dates
  drop_na(YMD) %>%
  # Theater, Company, Genre to factors for DT drop-downs
  mutate(Theater = as_factor(Theater)) %>%
  mutate(Company = as_factor(Company)) %>% 
  mutate(Genre = as_factor(Genre)) -> calendar

```

```{r}
DT::datatable(calendar, 
              # style = "bootstrap",
              extensions = 'Buttons',
              rownames = FALSE,
              filter = 'top',
              style = 'bootstrap4',
              class = 'compact table-striped',
              options = list(
                autoWidth = TRUE,
                pageLength = 25,
                dom = 'Brtilp',
                buttons = c('csv', 'print'),
                columnDefs = list(
                                  list(width = '100px',
                                       className = 'dt-right',
                                       targets  = 0, 
                                       # Order Date by YMD field
                                       orderData = 1),
                                  list(targets = 1,
                                       # Hide YMD field
                                       visible = FALSE),
                                  list(width = '70px',
                                       className = 'dt-center',
                                       targets = 2),
                                  list(width = '70px',
                                       targets = 3),
                                  list(width = '320px',
                                       targets = 4),
                                  list(width = '100px',
                                       targets = c(5, 6, 7))))
              ) %>% 
              # Make titles italic except "No title"
              formatStyle("Title", 
                          fontStyle = styleEqual('No title',
                                        'normal',
                                         default = 'italic')
              ) %>%
              # Concerts have NA for their work Type
              # Make their titles normal type
              formatStyle("Title", "Genre",
                          fontStyle = styleEqual(NA,
                                         'normal'))
  
```